#ifndef LIBCROCO_VERSION_NUMBER
#define LIBCROCO_VERSION_NUMBER 601
#endif

#ifndef LIBCROCO_VERSION
#define LIBCROCO_VERSION "0.6.1"
#endif

#ifndef G_DISABLE_CHECKS
#if 0
#define G_DISABLE_CHECKS 0
#endif
#endif

#if 1
#define CROCO_HAVE_LIBXML2 1
#endif

/* Too long */
#define cr_additional_sel_set_class_name cr_additional_sel_set_class_nam
#define cr_parser_try_to_skip_spaces_and_comments cr_parser_try_to_skip_sp_and_co
#define cr_declaration_parse_list_from_buf cr_declaration_par_list_fro_buf
#define cr_doc_handler_set_default_sac_handler cr_doc_handler_set_def_sac_hand
#define cr_doc_handler_associate_a_parser cr_doc_handler_associate_a_pars
#define cr_enc_handler_resolve_enc_alias cr_enc_handler_resolve_enc_alia
#define cr_font_size_set_predefined_absolute_font_size cr_ft_siz_set_predef_abs_ft_siz
#define cr_font_size_set_relative_font_size cr_font_size_set_rela_font_size
#define cr_font_size_set_absolute_font_size cr_font_size_set_abso_font_size
#define cr_font_size_get_smaller_predefined_font_size cr_ft_siz_get_small_pred_ft_siz
#define cr_font_size_get_larger_predefined_font_size cr_ft_siz_get_large_pred_ft_siz
#define cr_font_size_is_predefined_absolute_font_size cr_ft_size_is_predef_abs_ft_siz
#define cr_utils_read_char_from_utf8_buf cr_util_read_char_from_utf8_buf
#define cr_statement_new_at_charset_rule cr_statement_new_at_charset_rul
#define cr_statement_new_at_font_face_rule cr_stateme_new_at_font_face_rul
#define cr_om_parser_parse_paths_to_cascade cr_om_parser_parse_paths_to_cas
#define cr_om_parser_simply_parse_paths_to_cascade cr_om_par_simp_par_paths_to_cas
#define cr_parser_set_default_sac_handler cr_parser_set_default_sac_handl
#define cr_simple_sel_compute_specificity cr_simple_sel_compute_specifici
#define cr_style_set_props_to_initial_values cr_style_set_props_to_init_valu
#define cr_style_set_props_to_default_values cr_style_set_props_to_def_value
#define cr_sel_eng_register_pseudo_class_sel_handler cr_sel_eng_reg_pseud_cla_sel_ha
#define cr_sel_eng_unregister_pseudo_class_sel_handler cr_sel_eng_unreg_pseud_cl_sel_h
#define cr_sel_eng_unregister_all_pseudo_class_sel_handlers cr_sel_eng_unr_all_ps_cla_sel_h
#define cr_sel_eng_get_pseudo_class_selector_handler cr_sel_eng_get_pseud_cla_sel_ha
#define cr_sel_eng_get_matched_properties_from_cascade cr_sel_eng_get_mat_pro_from_cas
#define cr_simple_sel_prepend_simple_sel cr_simple_sel_prepend_simple_se
#define cr_simple_sel_dump_attr_sel_list cr_simple_sel_dump_attr_sel_lis
#define cr_statement_at_page_rule_set_sel cr_statement_at_pag_rul_set_sel
#define cr_statement_at_page_rule_get_sel cr_statement_at_pag_rul_get_sel
#define cr_statement_does_buf_parses_against_core cr_state_does_buf_par_again_cor
#define cr_statement_ruleset_parse_from_buf cr_state_ruleset_parse_from_buf
#define cr_statement_at_import_rule_parse_from_buf cr_stat_at_imp_rul_par_from_buf
#define cr_statement_at_media_rule_parse_from_buf cr_stat_at_med_rul_par_from_buf
#define cr_statement_at_charset_rule_parse_from_buf cr_stat_at_chars_rul_par_from_b
#define cr_statement_font_face_rule_parse_from_buf cr_stat_ft_fac_rul_par_from_buf
#define cr_statement_at_page_rule_parse_from_buf cr_stat_at_pag_rul_par_from_buf
#define cr_statement_ruleset_set_sel_list cr_statement_rules_set_sel_list
#define cr_statement_ruleset_get_sel_list cr_statement_rules_get_sel_list
#define cr_statement_ruleset_set_decl_list cr_statement_rules_set_decl_lis
#define cr_statement_ruleset_get_declarations cr_statement_rules_get_declarat
#define cr_statement_ruleset_append_decl2 cr_statement_rules_append_decl2
#define cr_statement_ruleset_append_decl cr_statement_ruleset_appen_decl
#define cr_statement_at_import_rule_set_imported_sheet cr_stat_at_imp_ru_set_imp_sheet
#define cr_statement_at_import_rule_get_imported_sheet cr_stat_at_imp_ru_get_imp_sheet
#define cr_statement_at_import_rule_set_url cr_state_at_import_rule_set_url
#define cr_statement_at_import_rule_get_url cr_state_at_import_rule_get_url
#define cr_statement_at_media_get_from_list cr_state_at_media_get_from_list
#define cr_statement_at_page_rule_set_declarations cr_stat_at_page_rule_set_declar
#define cr_statement_at_page_rule_get_declarations cr_stat_at_page_rule_get_declar
#define cr_statement_at_charset_rule_set_charset cr_state_at_chars_rul_set_chars 
#define cr_statement_at_charset_rule_get_charset cr_state_at_chars_rul_get_chars
#define cr_statement_at_font_face_rule_set_decls cr_stat_at_ft_fac_rul_set_decls
#define cr_statement_at_font_face_rule_get_decls cr_stat_at_ft_fac_rul_get_decls
#define cr_statement_at_font_face_rule_add_decl cr_stat_at_ft_face_rul_add_decl
#define cr_statement_dump_font_face_rule cr_statement_dump_font_face_rul
#define cr_style_white_space_type_to_string cr_style_white_space_typ_to_str
#define cr_style_position_type_to_string cr_style_position_typ_to_string
#define cr_style_resolve_inherited_properties cr_style_resolve_inherited_prop
#define cr_stylesheet_statement_get_from_list cr_stylesheet_stat_get_from_lis
#define cr_term_parse_expression_from_buf cr_term_par_expression_from_buf

